# Generated by Django 5.2.7 on 2025-10-19 03:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('serving_size', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='food_items_name_7242ab_idx'), models.Index(fields=['category'], name='food_items_categor_d07997_idx')],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Calories (kcal)', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.DecimalField(blank=True, decimal_places=2, help_text='Protein in grams', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates in grams', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.DecimalField(blank=True, decimal_places=2, help_text='Fats in grams', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, help_text='Sugar in grams', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, help_text='Sodium in milligrams', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('serving_size', models.CharField(blank=True, help_text='e.g., 1 cup, 100g, 1 piece', max_length=100, null=True)),
                ('servings', models.DecimalField(decimal_places=2, default=1.0, help_text='Number of servings', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('meal_date', models.DateField()),
                ('meal_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-meal_date', '-meal_time', '-created_at'],
                'indexes': [models.Index(fields=['user', 'meal_date'], name='meals_user_id_94af0e_idx'), models.Index(fields=['user', 'meal_type'], name='meals_user_id_90570f_idx'), models.Index(fields=['meal_date'], name='meals_meal_da_a9ba14_idx')],
            },
        ),
    ]
