# Generated by Django 5.2.6 on 2025-10-30 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_food_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True if created by user'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_unit',
            field=models.CharField(blank=True, help_text='e.g., cup, tbsp, piece', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_custom', 'created_by'], name='food_items_is_cust_4da792_idx'),
        ),
    ]
