# Generated by Django 5.2.7 on 2025-10-19 07:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal', models.IntegerField(default=10000, help_text='Daily step goal (1,000 - 100,000)', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Step Goal',
                'verbose_name_plural': 'Step Goals',
                'db_table': 'step_goals',
            },
        ),
        migrations.CreateModel(
            name='StepStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateField(default=datetime.date.today)),
                ('total_days_goal_met', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Step Streak',
                'verbose_name_plural': 'Step Streaks',
                'db_table': 'step_streaks',
            },
        ),
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('steps', models.IntegerField(help_text='Number of steps taken (0 - 200,000)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200000)])),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance covered in kilometers', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('calories_burned', models.IntegerField(blank=True, help_text='Estimated calories burned', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('active_minutes', models.IntegerField(blank=True, help_text='Active minutes (0 - 1440)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('fitbit', 'Fitbit'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('samsung_health', 'Samsung Health'), ('other', 'Other')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Steps',
                'verbose_name_plural': 'Daily Steps',
                'db_table': 'daily_steps',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_steps_user_id_30169b_idx'), models.Index(fields=['date'], name='daily_steps_date_415e1c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
