# Generated by Django 5.2.7 on 2025-10-10 16:34

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
