# Generated by Django 5.2.6 on 2025-10-25 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('running', 'Running (km)'), ('cycling', 'Cycling (km)'), ('swimming', 'Swimming (km)'), ('walking', 'Walking (km)'), ('weight', 'Weight (kg)'), ('calories', 'Calories Burned'), ('workouts', 'Number of Workouts'), ('strength', 'Strength Training (sessions)'), ('yoga', 'Yoga (sessions)'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value to achieve', max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current progress toward the goal', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='workouts_go_user_id_16ef12_idx'), models.Index(fields=['user', 'goal_type'], name='workouts_go_user_id_07885c_idx'), models.Index(fields=['end_date'], name='workouts_go_end_dat_76f671_idx')],
            },
        ),
    ]
