# Generated by Django 5.2.6 on 2025-10-30 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-workout_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='workout',
            name='workouts_wo_user_id_f1c995_idx',
        ),
        migrations.RemoveIndex(
            model_name='workout',
            name='workouts_wo_user_id_23c1bb_idx',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'workout_date'], name='workouts_user_id_52023e_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'status'], name='workouts_user_id_bee678_idx'),
        ),
        migrations.AlterModelTable(
            name='workout',
            table='workouts',
        ),
    ]
